import fs from 'node:fs/promises';
import path from 'node:path';
import { afterEach, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { processSession } from '../src/pipeline.js';
import { ensureSessionDirs, initStatus, newSessionId, sessionDir } from '../src/store.js';
import { defaultTranscriber } from '../src/whisper.js';
import type { TalkthruConfig } from '../src/config.js';
import { FIXTURE_HIERARCHY, FIXTURE_META, FIXTURE_VIDEO, GENERATED, ensureFixture, tempHome } from './helpers.js';

/**
 * The real thing: actual ffmpeg, actual whisper.cpp, actual model.
 *
 * Opt-in because it needs whisper.cpp installed and a ~150 MB model, and
 * because the narration audio is generated by macOS `say`. CI runs the golden
 * test instead, which replays this test's output through a fake transcriber.
 *
 *   npm run fixture && npm run fixture:audio && npm run e2e:whisper
 */
const ENABLED = process.env.TALKTHRU_E2E_WHISPER === '1';
const FIXTURE_AUDIO = path.join(GENERATED, 'fixture-audio.wav');

/** Lines spoken in the fixture, and the scene each one is about. */
const EXPECTED = [
  { atMs: 2_000, frame: 0, keywords: ['home', 'spacing'] },
  { atMs: 12_000, frame: 1, keywords: ['mars', 'card'] },
  { atMs: 22_000, frame: 2, keywords: ['fact', 'panel'] },
  { atMs: 32_000, frame: 3, keywords: ['settings', 'close'] },
  { atMs: 42_000, frame: 4, keywords: ['home', 'again'] },
  { atMs: 52_000, frame: 5, keywords: ['error', 'yellow'] },
];

let cfg: TalkthruConfig;
let cleanup: () => Promise<void>;

describe.skipIf(!ENABLED)('end to end with real whisper.cpp', () => {
  beforeAll(async () => {
    await ensureFixture();
    try {
      await fs.access(FIXTURE_AUDIO);
    } catch {
      throw new Error('Missing fixture audio. Run `npm run fixture:audio` (macOS only).');
    }
  }, 300_000);

  beforeEach(async () => {
    ({ cfg, cleanup } = await tempHome('e2e-whisper'));
  });
  afterEach(async () => cleanup());

  it('transcribes, segments and aligns six utterances to six scenes', async () => {
    const id = newSessionId();
    const dir = await ensureSessionDirs(cfg, id);
    await initStatus(cfg, id, 'local');
    for (const [src, name] of [
      [FIXTURE_VIDEO, 'video.mp4'],
      [FIXTURE_AUDIO, 'audio.wav'],
      [FIXTURE_META, 'meta.json'],
      [FIXTURE_HIERARCHY, 'hierarchy.json'],
    ] as Array<[string, string]>) {
      await fs.copyFile(src, path.join(dir, 'raw', name));
    }

    const { bundle } = await processSession(cfg, id, {
      transcriber: defaultTranscriber(cfg),
    });

    // Six scene cuts.
    expect(bundle.keyframes).toHaveLength(6);
    // Six spoken lines, split by real silence rather than by whisper's guess.
    expect(bundle.timeline).toHaveLength(EXPECTED.length);

    for (const [i, expected] of EXPECTED.entries()) {
      const entry = bundle.timeline[i]!;
      // Speech recognition is not deterministic enough to assert exact text,
      // but timing and binding must be exact — that is what this tool sells.
      expect(Math.abs(entry.startMs - expected.atMs), `utterance ${i} start`).toBeLessThan(1_200);
      expect(entry.keyframeIndex, `utterance ${i} frame`).toBe(expected.frame);

      const text = entry.utterance.toLowerCase();
      for (const keyword of expected.keywords) {
        expect(text, `utterance ${i} should mention "${keyword}": ${text}`).toContain(keyword);
      }
    }

    // The repeat of scene 0 shares its image and is labelled as a revisit.
    expect(bundle.keyframes[4]!.sameScreenAs).toBe(0);

    // No silence hallucinations reached the timeline.
    for (const entry of bundle.timeline) {
      expect(entry.utterance).not.toMatch(/\[.*\]/);
    }

    const markdown = await fs.readFile(path.join(sessionDir(cfg, id), 'session.md'), 'utf8');
    expect(markdown).toContain('back on the f00 screen');
    expect(markdown).toContain('occluded: system alert');
    // A 60 s session must stay far inside the budget.
    expect(bundle.estimatedTokens).toBeLessThan(2_000);
  }, 600_000);
});
